//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavaTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducatInfo
    {
        public int Educat_info_ID { get; set; }
        public int UserID { get; set; }
        public int SectionID { get; set; }
        public int UniID { get; set; }
        public int FieldID { get; set; }
        public int OrientationID { get; set; }
        public string ThesisDiss { get; set; }
        public string Avrage { get; set; }
        public string Stu_Graduate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> BeginStudy { get; set; }
        public Nullable<System.DateTime> YearGrad { get; set; }
    
        public virtual CrossSection CrossSection { get; set; }
        public virtual Fields Fields { get; set; }
        public virtual Orientation Orientation { get; set; }
        public virtual UniverCity UniverCity { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
