//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavaTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field_Lessons
    {
        public int FL_ID { get; set; }
        public int LessonID { get; set; }
        public int UserID { get; set; }
        public string ProblemSolving { get; set; }
        public string MakingVideo { get; set; }
        public string RelatedSoftware { get; set; }
    
        public virtual Lessons Lessons { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
