//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavaTraining.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Nava_DBEntities : DbContext
    {
        public Nava_DBEntities()
            : base("name=Nava_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<CrossSection> CrossSection { get; set; }
        public virtual DbSet<Fields> Fields { get; set; }
        public virtual DbSet<Orientation> Orientation { get; set; }
        public virtual DbSet<UniverCity> UniverCity { get; set; }
        public virtual DbSet<Lessons> Lessons { get; set; }
        public virtual DbSet<Field_Lessons> Field_Lessons { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<User_Lang> User_Lang { get; set; }
        public virtual DbSet<UserLogin> UserLogin { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<EducatInfo> EducatInfo { get; set; }
        public virtual DbSet<RejectInterView> RejectInterView { get; set; }
        public virtual DbSet<ResultInterView> ResultInterView { get; set; }
        public virtual DbSet<ResultItem> ResultItem { get; set; }
        public virtual DbSet<RegisterUser> RegisterUser { get; set; }
        public virtual DbSet<Special_Fields> Special_Fields { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<InterView> InterView { get; set; }
    }
}
