//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavaTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterUser
    {
        public int RegID { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string NationalNumber { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string MaritalStatus { get; set; }
        public string MilitaryService { get; set; }
        public string Address { get; set; }
        public string DescriptionArticles { get; set; }
        public string Workinprogress { get; set; }
        public string TypeOfEmployment { get; set; }
        public Nullable<int> TimeInWeek { get; set; }
        public Nullable<int> WageFullTime { get; set; }
        public Nullable<int> WagePartTime { get; set; }
        public string Telework { get; set; }
        public string Internship { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string DescriptionFull { get; set; }
        public string Rezome { get; set; }
        public System.DateTime DateSubmitInfo { get; set; }
        public bool EditInfo { get; set; }
        public int Status { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
    }
}
