//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavaTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RejectInterView
    {
        public int RejectID { get; set; }
        public int UserID { get; set; }
        public string CauseReject { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
    }
}
