//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavaTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultInterView
    {
        public int ResultID { get; set; }
        public int ItemID { get; set; }
        public int UserID { get; set; }
        public string SkillSpeaking { get; set; }
        public string PassionWork { get; set; }
        public string Sobriety { get; set; }
        public string Rhetorical { get; set; }
        public Nullable<System.DateTime> DateForWork { get; set; }
        public string VideoName { get; set; }
    
        public virtual ResultItem ResultItem { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
