//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavaTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Special_Fields
    {
        public int SP_FL { get; set; }
        public int FieldID { get; set; }
        public int SpecialID { get; set; }
        public int UserID { get; set; }
    
        public virtual Fields Fields { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual Speciality Speciality { get; set; }
    }
}
